programs:
    Dark And Darker:
        macros:
            - name: Test
              root:
                count: 1
                type: loop
                name: root
              globaldelay: 30
              hotkey: ""
            - name: New Macro 1
              root:
                count: 1
                type: loop
                name: root
                subactions:
                    - target: ""
                      searcharea:
                        name: ""
                        leftx: 0
                        topy: 0
                        rightx: 0
                        bottomy: 0
                      type: ocr
                      name: ""
                    - type: move
                      x: 0
                      "y": 0
                    - count: 1
                      type: loop
                      name: ""
                      subactions:
                        - type: move
                          x: 0
                          "y": 0
                        - type: move
                          x: 0
                          "y": 0
              globaldelay: 30
              hotkey: ""
        items: {}
        coordinates:
            2560x1440:
                points: {}
                searchareas: {}
